# Generated by Django 3.1.2 on 2020-10-21 13:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonPeraturan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Isikan judul/subject tentang peraturan yang diupload', max_length=255, verbose_name='*Judul/Subjek')),
                ('dokument', models.FileField(help_text='upload full dokument peraturan yang akan diunduh client', upload_to='', verbose_name='*Full Document Non-Peraturan')),
                ('thumbnail', models.ImageField(help_text='upload gambar tampilan dari buku/produk hukum non-peraturan', upload_to='', verbose_name='*Input Thumbnail Non-Peraturan')),
                ('col_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Col. Number')),
                ('authors', models.CharField(max_length=255, verbose_name='* Pengarang Buku')),
                ('judul_buku', models.CharField(blank=True, max_length=255, null=True, verbose_name='Judul Buku')),
                ('kota_terbit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Kota Terbit')),
                ('penerbit_buku', models.CharField(blank=True, max_length=255, null=True, verbose_name='Penerbit Buku')),
                ('tahun_terbit', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tahun Terbit Buku')),
                ('jilid', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jilid')),
                ('jumlah_halaman', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Halaman Buku')),
                ('tebal_buku', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tebal Buku')),
                ('subject_pengarang_buku', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Subjek & Pengarang Buku')),
                ('nomor_induk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor Induk')),
                ('status', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status Buku')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Non Peraturan',
                'verbose_name_plural': 'Data Non Peraturan',
                'db_table': 'jdih_data_non_peraturan',
            },
        ),
    ]
