# Generated by Django 3.1.2 on 2020-10-21 13:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunningTextHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='text akan tampil berjalan \t\tdengan bentuk marquee maksimal 250 Karakter', max_length=250)),
                ('set_default', models.BooleanField(default=False, verbose_name='Tampil sebagai default')),
                ('text_name', models.CharField(editable=False, max_length=255)),
                ('arah_scroll', models.CharField(choices=[('left', 'ke kiri'), ('right', 'ke kanan')], default='left', help_text='arah scroll teks dari kiri ke kanan, atau</br>\t\t\t\t\tdari kanan ke kiri', max_length=20)),
                ('kecepatan_scroll', models.IntegerField(default=5, help_text='kecepatan scroll \t\t\t\t\t\t\t\t\t\t\t\t\t\t</br>1-10 : lambat\t\t\t\t\t\t\t\t\t\t\t\t\t\t</br>11-20 : sedang\t\t\t\t\t\t\t\t\t\t\t\t\t\t</br>21-30 : cepat\t\t\t\t\t\t\t\t\t\t\t\t\t\t</br>30 keatas : sangat cepat')),
            ],
            options={
                'verbose_name': 'Text Berjalan',
                'verbose_name_plural': 'Text Berjalan',
                'db_table': 'jdih_running_text',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('image_name', models.CharField(editable=False, max_length=250)),
                ('image_description', models.CharField(help_text='Captions gambar\t\t\t\t\t\t(contoh :  Lembaga Pemasyarakatan Hukum Kota...)', max_length=250, verbose_name='deskripsi')),
                ('image_link', models.URLField(blank=True, help_text='Tambahkan link jika ada', max_length=250, null=True, verbose_name='link')),
                ('urutan', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Slideshow Beranda',
                'verbose_name_plural': 'Slideshow Beranda',
                'db_table': 'jdih_slide_image',
                'ordering': ['pk', 'image_name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(help_text='Gambar dengan ukuran resolusi 90x120 \t\t\t\t\t\t\tpixel atau dengan proposional yang serupa', upload_to='', verbose_name='logo logo')),
                ('banner', models.ImageField(help_text='Gambar dengan ukuran resolusi 640x120 \t\t\t\t\t\t\tpixel atau dengan proposional yang serupa', upload_to='', verbose_name='banner header')),
                ('footer', ckeditor.fields.RichTextField(verbose_name='copyright')),
                ('address', ckeditor.fields.RichTextField(verbose_name='alamat')),
                ('set_default', models.BooleanField(default=False, verbose_name='Tampil sebagai default')),
                ('template_name', models.CharField(editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Template Beranda',
                'verbose_name_plural': 'Template Beranda',
                'db_table': 'jdih_templates',
                'ordering': ['pk', 'template_name'],
            },
        ),
        migrations.CreateModel(
            name='URLModelResolve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('string_param', models.CharField(max_length=250)),
                ('id_param', models.IntegerField()),
            ],
            options={
                'db_table': 'jdih_url_model_resolve',
            },
        ),
    ]
