# Generated by Django 3.1.2 on 2020-10-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PranalaLuar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='nama url')),
                ('url', models.URLField(max_length=150, verbose_name='alamat url/pranala luar link')),
                ('urutan', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pranala Luar',
                'verbose_name_plural': 'Pranala Luar',
                'db_table': 'jdih_pranala_luar',
            },
        ),
    ]
