# Generated by Django 3.1.2 on 2020-10-21 13:55

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriPeraturan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Kategori Menu')),
                ('urutan', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='module_peraturan.kategoriperaturan', verbose_name='Kelompok Menu')),
            ],
            options={
                'verbose_name_plural': 'Kategori Peraturan',
                'db_table': 'jdih_kategori_peraturan',
            },
        ),
        migrations.CreateModel(
            name='DataListPeraturan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Isikan judul/subject tentang peraturan yang diupload', max_length=255)),
                ('tahun_peraturan', models.CharField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2020, help_text='tahun peraturan dikeluarkan', max_length=4)),
                ('nomor_peraturan', models.CharField(help_text='nomor peraturan dikeluarkan', max_length=255)),
                ('dokument', models.FileField(help_text='upload full dokument peraturan yang akan diunduh client', upload_to='')),
                ('status', models.CharField(choices=[('-', ''), ('dicabut', 'Dicabut'), ('mencabut', 'Mencabut'), ('diubah', 'Diubah'), ('mengubah', 'Mengubah'), ('batal', 'Batal')], default='-', max_length=50)),
                ('catalog_tajuk_entri', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tajuk Entri Utama')),
                ('catalog_judul_seragam', models.CharField(blank=True, max_length=255, null=True, verbose_name='Judul Seragam')),
                ('catalog_bentuk_nomor_tahun', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bentuk, Nomor, Tahun Peraturan')),
                ('catalog_tanggal_bulan_tahun', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tanggal, Bulan, dan Tahun Peraturan')),
                ('catalog_perihal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Perihal / Tentang')),
                ('catalog_pengesahan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tempat Pengesahan')),
                ('catalog_tahun_pengesahan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tahun Peraturan')),
                ('catalog_sumber_teks', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sumber Teks Peraturan')),
                ('catalog_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subjek Peraturan')),
                ('catalog_singkatan_peraturan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Singkatan Bentuk Peraturan')),
                ('catalog_lokasi_penyimpanan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lokasi Penyimpanan')),
                ('abstract_subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subjek Abstrak Peraturan')),
                ('abstract_tahun', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tahun Abstrak Peraturan')),
                ('abstract_singkatan_peraturan', models.CharField(blank=True, max_length=255, null=True, verbose_name='Singkatan Bentuk Peraturan')),
                ('abstract_nomor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nomor Peraturan')),
                ('abstract_sumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sumber Peraturan')),
                ('abstract_jumlah_halaman', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jumlah Halaman Peraturan')),
                ('abstract_jenis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jenis/Bentuk Peraturan')),
                ('abstract_tentang', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Tentang Peraturan')),
                ('abstract_deskripsi', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Abstrak Peraturan ini Adalah')),
                ('abstract_dasar_hukum', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Dasar Hukum Undang-Undang ini adalah')),
                ('abstract_diatur', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Dalam Undang-Undang ini diatur tentang')),
                ('abstract_catatan', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='CATATAN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(help_text='kategori/jenis peraturan yang diupload', on_delete=django.db.models.deletion.CASCADE, to='module_peraturan.kategoriperaturan')),
            ],
            options={
                'verbose_name_plural': 'Data Peraturan',
                'db_table': 'jdih_data_peraturan',
            },
        ),
    ]
