# Generated by Django 3.1.2 on 2020-10-22 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module_peraturan', '0002_auto_20201022_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalistperaturan',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='module_admin_list.userjdihcostum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datalistperaturan',
            name='updated_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_peraturan_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datalistperaturan',
            name='dokument',
            field=models.FileField(help_text='upload full dokument peraturan yang akan diunduh client', upload_to='file/docs', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docs', 'docx'])]),
        ),
    ]
