# Generated by Django 3.1.2 on 2020-10-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KotakSaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('nama_pengirim', models.CharField(max_length=100)),
                ('email_pengirim', models.CharField(max_length=100)),
                ('subyek', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('status_terbaca', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inbox Kotak Saran',
                'verbose_name_plural': 'Inbox Kotak Saran',
                'db_table': 'jdih_kotak_saran',
            },
        ),
    ]
