# Generated by Django 3.1.2 on 2020-10-22 03:20

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPermission',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            options={
                'verbose_name': 'Group Permissions',
                'verbose_name_plural': 'Group Permissions',
                'db_table': 'jdih_admin_permissions',
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionList',
            fields=[
            ],
            options={
                'verbose_name': 'Permission List',
                'verbose_name_plural': 'Permission List',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserJDIHCostum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='Alamat email pengguna', max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(help_text='Username harus unik tidak diperbolehkan duplikat', max_length=20, unique=True, verbose_name='Nama Pengguna')),
                ('name', models.CharField(help_text='Nama Lengkap Pengguna', max_length=50, verbose_name='Nama Lengkap')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Status Admin')),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='module_admin_list.grouppermission')),
                ('user_permissions', models.ManyToManyField(blank=True, to='module_admin_list.PermissionList')),
            ],
            options={
                'verbose_name': 'Admin List',
                'verbose_name_plural': 'Admin List',
                'db_table': 'jdih_admin',
            },
        ),
    ]
